fc/blueprints/auth.py
# -*- coding: utf-8 -*-

from flask import render_template, flash, redirect, url_for, Blueprint
from flask_login import login_user, logout_user, login_required, current_user, login_fresh, confirm_login
from fc.emails import send_confirm_email, send_reset_password_email
from fc.extensions import db
from fc.forms.auth import LoginForm, RegisterForm, ForgetPasswordForm, ResetPasswordForm
from fc.models import User
from fc.settings import Operations
from fc.utils import generate_token, validate_token



# Subclass registration
auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user is not None and user.validate_password(form.password.data):
            login_user(user, form.remember_me.data)
            flash('Login success.', 'info')
            return redirect(url_for('main.explore'))
        flash('Invalid email or password.', 'warning')
    return render_template('auth/login.html', form=form)


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logout success.', 'info')
    return redirect(url_for('main.index'))


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = RegisterForm()
    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data.lower()
        username = form.username.data

        password = form.password.data


        user = User(name=name, email=email, username=username)
        user.set_password(password)

        db.session.add(user)
        db.session.commit()
        token = generate_token(user=user, operation='confirm')
        send_confirm_email(user=user, token=token)

        flash('Confirm email sent, check your inbox.', 'info')

        return redirect(url_for('.login'))

    return render_template('auth/register.html', form=form)


@auth_bp.route('/confirm/<token>')
@login_required
def confirm(token):
    if current_user.confirmed:
        return redirect(url_for('main.index'))

    if validate_token(user=current_user, token=token, operation=Operations.CONFIRM):
        flash('Account confirmed.', 'success')
        return redirect(url_for('main.index'))
    else:
        flash('Invalid or expired token.', 'danger')
        return redirect(url_for('.resend_confirm_email'))


@auth_bp.route('/resend-confirm-email')
@login_required
def resend_confirm_email():
    if current_user.confirmed:
        return redirect(url_for('main.index'))

    token = generate_token(user=current_user, operation=Operations.CONFIRM)
    send_confirm_email(user=current_user, token=token)
    flash('New email sent, check your inbox.', 'info')
    return redirect(url_for('main.index'))


@auth_bp.route('/forget-password', methods=['GET', 'POST'])
def forget_password():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = ForgetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user:
            token = generate_token(user=user, operation=Operations.RESET_PASSWORD)
            send_reset_password_email(user=user, token=token)

            flash('Password reset email sent, check your inbox.', 'info')
            return redirect(url_for('.login'))
        flash('Invalid email.', 'warning')
        return redirect(url_for('.forget_password'))
    return render_template('auth/reset_password.html', form=form)


@auth_bp.route('/reset-password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = ResetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user is None:
            return redirect(url_for('main.index'))
        if validate_token(user=user, token=token, operation=Operations.RESET_PASSWORD,
                          new_password=form.password.data):
            flash('Password updated.', 'success')
            return redirect(url_for('.login'))
        else:
            flash('Invalid or expired link.', 'danger')
            return redirect(url_for('.forget_password'))
    return render_template('auth/reset_password.html', form=form)

fc/blueprints/main.py
# -*- coding: utf-8 -*-
import json

from flask import render_template, Blueprint, request, jsonify
from flask_login import login_required


main_bp = Blueprint('main', __name__)


@main_bp.route('/')
def index():
    return render_template('index.html')


@main_bp.route('/explore')
@login_required
def explore():

    return render_template('main.html')


@main_bp.route('/search')
def search():
    return render_template('search.html')

fc/templates/base.html
{% from 'bootstrap/nav.html' import render_nav_item %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block head %}
        <title>{% block title %}{% endblock %} - Covid-19 analysis</title>
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
        {% block styles %}
            <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='open-iconic/font/css/open-iconic-bootstrap.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
        {% endblock styles %}
    {% endblock head %}
</head>

<body>
{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('main.index') }}">
                <img src="{{ url_for('static', filename='favicon.ico') }}" alt="Yiqing">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                    aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor01">
                <div class="navbar-nav mr-auto">
                    {{ render_nav_item('main.index', 'Home') }}
                    {{ render_nav_item('main.explore', 'Explore') }}
<!--                    <form action="{{url_for('main.explore') }}" class="form-inline my-2 my-lg-0">-->

<!--                        <input type="text" name="q" class="form-control mr-sm-1" placeholder="请输入水果:" required>-->
<!--                        <button class="btn btn-light my-2 my-sm-0" type="submit">-->
<!--                            <span class="oi oi-magnifying-glass"></span>-->
<!--                        </button>-->

<!--                    </form>-->
                </div>
                <div class="navbar-nav ml-auto">
                {% if current_user.is_authenticated %}
                    <div class="dropdown nav-item">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-expanded="false">
                            {{ current_user.name }}<span class="caret"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" role="menu">
                            <h6 class="dropdown-header">Logged in as {{ current_user.username }}</h6>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ url_for('auth.logout') }}">
                                <span class="oi oi-power-standby"></span> Logout
                            </a>
                        </div>
                    </div>
                {% else %}
                    <a class="btn btn-outline-primary" href="{{ url_for('auth.login') }}">Login</a>&nbsp;&nbsp;
                    <a class="btn btn-primary" href="{{ url_for('auth.register') }}">Join us</a>
                {% endif %}
                </div>
            </div>
        </div>
    </nav>
{% endblock %}

<main>
    <div class="container">
        {% for message in get_flashed_messages(with_categories=True) %}
            <div class="alert alert-{{ message[0] }}">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message[1] }}
            </div>
        {% endfor %}
        {% block content %}{% endblock %}
        {% block footer %}
            <footer>
                <p class="float-left">
                    <small>&copy; 2022
                        <a href="https://www.nhs.uk/conditions/coronavirus-covid-19/how-to-avoid-catching-and-spreading-coronavirus-covid-19/" title="Written">Anti-epidemic tips </a> --
                        <a href="https://www.who.int/emergencies/diseases/novel-coronavirus-2019/advice-for-public/when-and-how-to-use-masks?adgroupsurvey={adgroupsurvey}&gclid=Cj0KCQjw3v6SBhCsARIsACyrRAlbDRR2nTEsTyB_Dv5eSL0QMb6ZLwYRt7anpHMS9KOlbEg95ExmRXAaAtDzEALw_wcB" title="Fork me ">Wearing a face mask</a> --
                        <a href="https://www.nhs.uk/conditions/coronavirus-covid-19/testing/" title="A  project">Timed testing</a>
                    </small>
                </p>
                <p class="float-right">
                    <small>Love and hope to spread faster than a virus.</small>
                </p>
            </footer>
        {% endblock %}
    </div>
</main>

{% block scripts %}
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    {{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
{% endblock %}
</body>
</html>

fc/templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-8">
                <img src="{{ url_for('static', filename='images/indexs.jpg') }}" class="rounded img-fluid">
            </div>
            <div class="col-md-4 align-self-center">
                <h1>Covid-19 visualisation platform</h1>
                <p>Join us ！！！</p>
                <p><a class="btn btn-primary btn-lg" href="{{ url_for('auth.register') }}">Join Now</a></p>
            </div>
        </div>
    </div>
{% endblock %}

fc/templates/main.html
<html>
<head>
    <meta charset="utf-8">
    <title>Covid-19 visualisation platform</title>
    <link rel="shortcut icon" href="{{ url_for('static',filename='images/lol.ico') }}" type="image/x-icon"/>

    <link rel="stylesheet" href="{{ url_for('static',filename='css/comon0.css') }}">
</head>
<body>


<div class="back"></div>
<div class="head">
    <div class="ye">Haoyu Wang</div>
    <style>
    a{ color:#00F}
    a:hover{ color:#F00}/* 鼠标经过悬停字体颜色 (Mouse over hover font colour)*/
    /* css 注释说明：以上代码为设置html中超链接统一字体颜色
    (The above code is to set a uniform font colour for hyperlinks in html)
     */
    .div a{ color:#090}
    .div a:hover{ color:#090}
    /* css注释说明：以上代码为设置html中.div对象内超链接字体颜色
    (The above code is to set the font colour of the hyperlink in the .div object in html)
    */

    </style>
    <div class="weather"><span id="showTime"></span></div>
    <h1>Covid-19 visualisation platform</h1>
</div>

<script>
    var t = null;
    t = setTimeout(time, 1000);/*開始运行 (Start running)*/
    function time() {
        clearTimeout(t);/*清除定时器 (Clear Timer)*/
        dt = new Date();
        var y = dt.getFullYear();
        var mt = dt.getMonth() + 1;
        var day = dt.getDate();
        var h = dt.getHours();
        var m = dt.getMinutes();
        var s = dt.getSeconds();
        document.getElementById("showTime").innerHTML = y + "/" + mt + "/" + day + " " + h + ":" + m + ":" + s ;
        t = setTimeout(time, 1000);
    }


</script>
<div style="background:#000d4a url('../static/images/bg4.jpg') center top;" class="mainbox">
    <ul class="clearfix">
        <li>
            <div class="boxall" style="height:400px;">
                <div class="alltitle">The top 5 countries with new cases</div>
                <div class="navboxall" id="echart5"></div>
            </div>
            <div class="boxall" style="height:260px;">
                <div class="alltitle">The number of new cases in each country </div>
                <div class="navboxall">
                    <div class="wraptit">
                        <span>Country</span><span>New cases</span><span>New Deaths</span><span>New infections added</span>
                    </div>
                    <div class="wrap">
                        <ul id="heropick">

                        </ul>
                    </div>

                </div>
            </div>
            <div class="boxall" style="height:260px;">
                <div class="alltitle">The top 5 countries with total cases</div>

                <div class="navboxall" id="echart1"></div>
            </div>
        </li>
        <li>
            <div class="boxall" style="height:230px">
                <div class="clearfix navboxall" style="height: 100%">
                    <!--                            <div class="pulll_left num">-->
                    <!--                                <div class="numbt">General information<span>(单位：元)</span></div>-->
                    <!--                                <div class="numtxt">19382721 </div>-->
                    <!--                            </div>-->
                    <div class="pulll_left zhibiao">
                        <div class="zb1"><span id="winratetop"></span>
                            <div id="zb1"></div>
                        </div>
                        <div class="zb2"><span id="killtop"></span>
                            <div id="zb2"></div>
                        </div>

                    </div>
                    <div style="display:inline-block" class="pulll_right zhibiao ">
                        <div class="zb3"><span id="ineyetop"></span>
                            <div id="zb3"></div>
                        </div>
                        <div class="zb4"><span id="memberkdatop"></span>
                            <div id="zb4"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="boxall" style="height:420px">
                <div class="alltitle">Global Epidemic Display Chart</div>
                <div class="navboxall" id="echart4"></div>

            </div>
            <div class="boxall" style="height:270px">
                <div class="alltitle">The 5 countries with the worst outbreaks</div>
                <div class="navboxall" id="echart3"></div>
            </div>
        </li>
        <li>
            <div class="boxall" style="height:300px">
                <div class="alltitle">Most restored countries</div>
                <div class="navboxall">
                    <table class="table1" width="100%" border="0" cellspacing="0" cellpadding="0">
                        <tbody id="wingstop5">
                        <tr>
                            <th scope="col" class="toptop">Ranking</th>
                            <th scope="col">Country</th>
                            <th scope="col">Number of people recovered</th>

                        </tr>
                        <tr>
                            <td><span>1</span></td>
                            <td></td>
                            <td><br></td>
                            <td><br></td>
                        </tr>
                        <tr>
                            <td><span>2</span></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>

                        <tr>
                            <td><span>3</span></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><span>4</span></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><span>5</span></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="boxall" style="height:310px">
                <div class="alltitle">Top three countries in terms of number of existing consultations</div>
                <div class="navboxall" id="echart6"></div>
            </div>

            <div class="boxall" style="height:310px">
                <div class="alltitle">Top 3 countries with the highest number of deaths</div>
                <div class="navboxall" id="echart2"></div>
            </div>


        </li>
    </ul>

</div>
</div>


<script type="text/javascript" src="{{ url_for('static',filename='js/jquery.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static',filename='js/echarts.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static',filename='js/jquery.liMarquee.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static',filename='js/jquery.cxselect.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static',filename='js/get_data.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static',filename='js/world.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static',filename='js/china.js') }}"></script>
</body>
</html>